// this code is autogenerated using ansvia-vscode extension.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for Session
@immutable
class Session extends Equatable {
  // final int id;
  final int $param.service_name_camel_case$Id;
  final String token;

  Session(this.$param.service_name_camel_case$Id,this.token)
      : super([$param.service_name_camel_case$Id,token,]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    // data["id"] = this.id;
    data["$param.service_name_snake_case$_id"] = this.$param.service_name_camel_case$Id;
    data["token"] = this.token;
    return data;
  }

  static Session fromMap(Map<String, dynamic> data) {
    return Session(
        data['$param.service_name_snake_case$_id'] as int, data['token'] as String);
  }

  Session copy({int $param.service_name_camel_case$Id, String token }) {
    return Session($param.service_name_camel_case$Id ?? this.$param.service_name_camel_case$Id, token ?? this.token);
  }
}