- hosts: "{{server}}"
  remote_user: "{{remote_user}}"
  gather_facts: no
  tasks:
    - name: Upload sources
      synchronize:
        src: "{{project_dir}}"
        dest: "{{dest_server_path}}"
        checksum: yes
        recursive: yes
        delete: yes
    - name: Upload Git info
      copy:
        src: "GIT_REV"
        dest: "{{dest_server_path}}/$name_snake_case$/GIT_REV"
    - name: Patch db if any
      command: diesel migration run
      environment:
        DATABASE_URL: "{{DATABASE_URL}}"
        FCM_SERVER_KEY: "{{FCM_SERVER_KEY}}"
      args:
        chdir: "{{dest_server_path}}/$name_snake_case$"
    - name: Build binary
      command: make release
      environment:
        DATABASE_URL: "{{DATABASE_URL}}"
        FCM_SERVER_KEY: "{{FCM_SERVER_KEY}}"
      args:
        chdir: "{{dest_server_path}}/$name_snake_case$"
    - name: Install binary
      copy:
        src: "{{dest_server_path}}/$name_snake_case$/target/release/$name_snake_case$_server"
        remote_src: true
        dest: "/usr/local/bin/$name_snake_case$_server"
        mode: "0755"
    - name: Create service
      template:
        src: $name_snake_case$_server.service.j2
        dest: "/etc/systemd/system/$name_snake_case$_server.service"
    - name: Make sure service running
      systemd:
        state: restarted
        name: $name_snake_case$
        daemon_reload: yes

