- hosts: "{{server}}"
  remote_user: "{{remote_user}}"
  gather_facts: no
  tasks:
    - name: Upload dist package
      synchronize:
        src: "{{project_dir}}/frontends/$name_snake_case$_web/dist/"
        dest: "{{dest_server_path}}/$name_snake_case$_web"
        checksum: yes
        recursive: yes
        delete: yes
        # rsync_opts:
        #   - "--exclude=.env"
    - name: set owner
      file:
        path: "{{dest_server_path}}/$name_snake_case$_web"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
