//! Wrapper untuk meng-import struct dari protobuf autogenerated output files.
//! 

#![allow(bare_trait_objects)]
#![allow(renamed_and_removed_lints)]
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

mod inner {
    include!(concat!(env!("OUT_DIR"), "/$name_snake_case$.rs"));
}

pub use self::inner::{$param.service_name_camel_case$};
